routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin/users', 'admin\UserController');

Route::get('/admin', function () {
    return view('layouts.adminlayout');
});

Route::get('/home', 'admin\UserController@index')->name('users.index');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';
    protected $guarded = [];



    public function questions() {
        return $this->hasMany('App\Question');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

app/Http/Controllers/admin/CategoryController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/category/edit.blade.php
@extends('layouts.adminlayout')

@section('content')
    <div class="col-xl-12">
        <section class="hk-sec-wrapper">
            <h5 class="hk-sec-title">Category Details</h5>
            <p class="mb-25"></p>
            <div class="row">
                <div class="col-sm">
                    <form action="{{route('users.update',$user->id)}}" method="post">
                        @csrf
                        @method('put')
                        <div class="row">
                            <div class="form-group col-lg-5">
                                <label for="username">Name</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">@</span>
                                    </div>
                                    <input class="form-control" id="username" name="name" value="{{$user->name}}" type="text">
                                </div>
                            </div>
                            <div class="form-group col-lg-5">
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input class="form-control" id="email" name="email" value="{{$user->email}}" type="email">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-5 mb-10">
                                <label for="country">isActive</label>
                                <select class="form-control custom-select d-block w-100" id="active" name="active">
                                    <option value="0"  @if($user->active == 0) selected @endif">No</option>
                                    <option value="1"  @if($user->active == 1) selected @endif>Yes</option>
                                </select>
                            </div>
                            <div class="col-md-4 mb-10">
                                <label for="state">isAdmin</label>
                                <select class="form-control custom-select d-block w-100" id="admin" name="admin">
                                    <option value="0" @if($user->admin == 0) selected @endif">No</option>
                                    <option value="1"  @if($user->admin == 1) selected @endif>Yes</option>
                                </select>
                            </div>

                        </div>
                        <hr>
                        <div class="form-group col-lg-10">
                            <p>About user</p>
                            <textarea name="about" id="" cols="60" rows="5">{{$user->about}}</textarea>

                        </div>
                        <div class="row">
                            <div class="col-md-8 form-group">
                                <label for="avatar">Avatar</label>
                                <input class="form-control" id="avatar" value="{{$user->avatar}}" type="text">
                            </div>

                        </div>

                        <hr>
                        <button class="btn btn-primary" type="submit">Edit</button>
                    </form>
                </div>
            </div>
        </section>
    </div>



@stop

resources/views/admin/category/index.blade.php
@extends('layouts.adminlayout')


@section('content')

        <table class="table table-dark table-bordered mb-0">
            <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>email</th>
                <th>name</th>
                <th>date registered</th>
                <th>Role</th>
                <th>Active?</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($users as $user)
                <tr>
                    <th scope="row">{{$user->id}}</th>
                    <td>{{$user->email}}</td>
                    <td>{{$user->name}}</td>
                    <td>{{date('Y-m-d h:i:s', strtotime($user->created_at))}}</td>
                    <td>
                        @if($user->admin == 1)
                            <span class="badge badge-danger">admin</span>
                         @else
                            <span class="badge badge-primary">Regular</span>

                        @endif
                    </td>
                    <td>
                        @if($user->active == 1)
                            <span class="badge badge-soft-info">Yes</span>
                        @else
                            <span class="badge badge-soft-primary">No</span>

                        @endif
                    </td>
                    <td>
                        <a href="{{route('users.edit',$user->id)}}"><span class="badge badge-primary">Edit</span> </a>
                        <a href=""><span class="badge badge-danger">Delete</span> </a>

                    </td>
                </tr>
            @endforeach


            </tbody>
        </table>


@stop